--Thủ tục
CREATE 
--ALTER 
PROC TENPROC
	@TENTS1 VARCHAR(30), -- INPUT
	@TENTS2 INT OUT --OUTPUT
AS --KẾT THÚC KHAI BÁO THỦ TỤC 
	--CÂU LỆNH 
	--KHAI BÁO BIẾN
	DECLARE @TENBIEN INT, @TENBIEN2 VARCHAR(3)
	--GÁN GIÁ TRỊ
	SET @TENBIEN = 1
	SELECT @TENBIEN = 2, @TENBIEN2 = 3
	SELECT @TENBIEN = TENPHIM --> LẤY DÒNG CUỐI TRONG BẢNG
	FROM MUONPHIM

	--VÒNG LẶP
	WHILE (@TENBIEN < 10)
	BEGIN
		--LỆNH XỬ LÍ
		SET @TENBIEN = @TENBIEN +1
	END
	--CÂU LỆNH T-SQL
	SELECT * FROM MUONPHIM
	INSERT MUONPHIM(TENPHIM) 
	VALUES(@TENBIEN2)

	RETURN @TENBIEN --KIỂU SỐ NGUYÊN
GO
DECLARE @KQ INT, @KQ1 INT
EXEC @KQ1 = TENPROC 'AA',  @KQ OUT
--VD: THÊM 1 MUONPHIM
GO
CREATE 
--ALTER
PROCEDURE THEM_MP
	@CMND VARCHAR(10),
	@TENPHIM VARCHAR(30),
	@STTTAP INT
AS
	IF @CMND IS NULL 
	BEGIN
		RETURN 0 -- LỖI
	END
	IF @TENPHIM NOT IN (SELECT TENPHIM FROM PHIM)
		RETURN 0
	IF @STTTAP <= 0 
		RETURN 0
	INSERT MUONPHIM(CMND,TENPHIM,STTTAP,NGAYMUON)
	VALUES(@CMND,@TENPHIM,@STTTAP,GETDATE())

	IF @@ERROR = 0
		RETURN 1
GO --KẾT THÚC THỦ TỤC
DECLARE @KQ INT
EXEC @KQ = THEM_MP '11111','MA',1
IF @KQ = 1
	PRINT 'THEM THANH CONG'

SELECT * FROM MUONPHIM

--Hàm: 2 LOẠI TRẢ VỀ KIỂU DỮ LIỆU : INT, FLOAT, DATE, | TRẢ VỀ BẢNG
--DÙNG TRONG THỦ TỤC, TRIGGER
--LOẠI TRẢ VỀ KIỂU DỮ LIỆU
GO
CREATE 
--ALTER
FUNCTION F_TENFUNCTION (
		@TENTS INT,
		@TENTS2 FLOAT
	)
RETURNS INT
AS
BEGIN
	RETURN 1
END
--TÍNH SỐ PHIM MƯỚN CỦA CMND TRUYỀN VÀO
CREATE FUNCTION F_TINHSOPHIM (@CMND VARCHAR(10))
RETURNS INT
AS
BEGIN
	--CHỈ ĐƯỢC DÙNG CÁC LỆNH SELECT (KO DÙNG i, d, u)
	DECLARE @KQ INT
	IF @CMND IS NULL
		RETURN -1
	SELECT @KQ = COUNT(*) FROM MUONPHIM WHERE @CMND = CMND
	RETURN @KQ
END
SELECT DBO.F_TINHSOPHIM('1111')
---TRẢ BẢNG: DỮ LIỆU PHỨC TẠP DÙNG FUNCTION NÀY ĐỂ TẠO BẢNG 
CREATE 
--ALTER
FUNCTION F_MUONPHIM(@CMND VARCHAR(10))
RETURNS TABLE
AS
	RETURN (SELECT MUONPHIM.*, PHIM.NAMSX FROM MUONPHIM JOIN PHIM ON PHIM.TENPHIM = MUONPHIM.TENPHIM WHERE CMND = @CMND)


	SELECT * FROM F_MUONPHIM('12334') A JOIN PHIM P ON A.TENPHIM = P.TENPHIM
--Trigger: CÀI RBTV TỰ ĐỘNG KHI THỰC HIỆN THAO TÁC THÊM - XÓA - SỬA DỮ LIỆU
GO
--1 CMND KHÔNG ĐƯỢC MƯỚN 2 PHIM
--KHÔNG CÓ THAM SỐ VÀO (GIÁ TRỊ INPUT = DÒNG ĐƯỢC THÊM)
--TẠO 2 BẢNG: INSERTED :DLIEU MỚI | DELETED: DỮ LIỆU CŨ
CREATE 
--ALTER
TRIGGER TR_TENTRIGGER
ON MUONPHIM
FOR INSERT
AS
	SELECT * FROM inserted
	SELECT * FROM deleted
	SELECT * FROM MUONPHIM
	--ĐIỀU KIỆN VI PHẠM
	IF EXISTS (SELECT I.CMND FROM inserted I WHERE DBO.F_TINHSOPHIM(CMND) > 1) 
	BEGIN
		RAISERROR('ER1:LOI 1111',16,1)
		ROLLBACK TRAN
	END
GO
INSERT MUONPHIM (CMND,TENPHIM,STTTAP,NGAYMUON)
VALUES('11111','MA',2,GETDATE())